name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Автоматический деплой при пуше в main
  workflow_dispatch:  # Возможность запустить вручную

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Отключаем Jekyll (чтобы _next/ загружался корректно)
        run: touch .nojekyll

      - name: Загрузка артефактов
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Деплоим весь репозиторий

      - name: Деплой на GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
