name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Установка зависимостей
        run: npm install

      - name: Сборка и экспорт Next.js
        run: |
          npm run build
          npm run export
          mv out public  # GitHub Pages требует папку "public"

      - name: Загрузка артефактов
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # Загружаем статику в GitHub Actions

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Деплой в GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public  # Папка с экспортированным Next.js
